# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_auto_20210820_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergroup',
            name='contact_person_number',
            field=models.CharField(default=int, max_length=150),
            preserve_default=False,
        ),
    ]
