# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_farmergroup_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='month_joined',
            field=models.PositiveIntegerField(blank=True, choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')], null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='year_joined',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
