# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_auto_20211016_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmergroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
