# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_auto_20211016_1126'),
        ('activity', '0002_auto_20210820_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='farmer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.FarmerGroup'),
        ),
    ]
