# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210820_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ManyToManyField(blank=True, null=True, to='conf.District'),
        ),
    ]
