# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='system_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
