# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-02 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_system_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
