# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20210902_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='system_theme',
            field=models.CharField(blank=True, choices=[('app_theme', 'app_theme'), ('app_theme_a', 'app_theme_a'), ('app_theme_b', 'app_theme_b'), ('app_theme_c', 'app_theme_c'), ('app_theme_d', 'app_theme_d'), ('app_theme_e', 'app_theme_e'), ('app_theme_f', 'app_theme_f'), ('app_theme_g', 'app_theme_g')], max_length=64, null=True),
        ),
    ]
