# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-03 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_system_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
